from typing import Protocol
from maze import Maze
from maze.core.direction import Direction

class PromptStyle(Protocol):

    def preamble(self, maze: Maze) -> str: ...

    def describe_direction(self, direction: Direction, maze: Maze) -> str: ...

    def step_epilogue(self, maze: Maze) -> str: ...

    def steps_summary(self, maze: Maze) -> str: ...

    def last_move_info(self, maze: Maze) -> str: ...

    def illegal_answer(self) -> str: ...

    def illegal_direction(self) -> str: ...
