from typing import Protocol
from maze import Maze
from maze.core.direction import Direction


class PromptStyle(Protocol):
    def preamble(
        self,
        maze: Maze,
        provide_legal_output_hint: bool,
        provide_spacial_awerness_hint: bool,
    ) -> str: ...

    def step_preamble(self, maze: Maze) -> str: ...

    def describe_direction(self, direction: Direction, maze: Maze) -> str: ...

    def steps_summary(self, maze: Maze, steps_provided: int) -> str: ...

    def last_move_info(self, maze: Maze) -> str: ...

    def possible_moves(self, maze: Maze) -> str: ...

    def step_epilogue(self) -> str: ...

    def illegal_answer(self) -> str: ...

    def illegal_direction(self, illegal_direction: str) -> str: ...
