name: Execute example run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Run program
        run: |
          nix develop --command just run
